### ISSUE TITLE
icon.png is broken

### ISSUE THREAD

**Issue by jinkwon** [bitwit/strider-scheduler#1]
Hi,
I installed this plugin, and I found icon.png is broken.

**Comment by bitwit** [comment]
thank you, I will look in to this

**Comment by emcniece** [comment]
@bitwit what are the chances of getting that icon uploaded?

**Comment by bitwit** [comment]
@emcniece 's PR should have now fixed this

**Comment by emcniece** [comment]
<img width="460" alt="screen shot 2016-10-17 at 9 09 38 pm" src="https://cloud.githubusercontent.com/assets/1182187/19464064/1bf12f2a-94ae-11e6-8c6a-2dff20dff7a2.png">
